print("******************************************")
print("EMPLOYEE EXPENSE MANAGEMENT SYSTEM")
print("******************************************")
print("1. Client meetings")
print("2. business travel")
print("3. food ")
print("4. taxis")
print("5. hotels")
print("6. office supplies")
print("7. conferences")
n = int(input("Enter your choice: "))
r=input("Do have receipt?:(yes/no) ")
report=input(" is it pre aproved by manager?:(yes/no) ")
if report=="yes":
    limit=int(input("Enter the pre aproved expence amount: "))