a = 10
b = 20
print(a == b)
print(a != b)
print(a < b)
print(a > b)
print(a <= b)
print(a >= b)
print("apple" == "apple")
print("apple" == "Apple")
print("10" == 10)
print("***********")
print(bool(True))
print(bool(False))
print(bool(0))
print(bool(1))
print(bool(''))
print(bool('Python'))
print(bool(None))
