print("****************************************")
print("PYTHON DAY 1")
print("****************************************")
print("NAME : BASANI INNA SWAGATH REDDY")
print("learning : PYTHON")
print("DAY 1")
PRINT(10+20)
print(10*20)
print(100/4)
print(100//4)