print(" Personal Life Stats CLI ")
name=input("ENTER YOUR NAME")
age=int(input("ENTER THE AGE"))
weight=int(input("ENTER THE WEIGHT"))
gw=int(input("ENTER THE GOAL WEIGHT"))
height=int(input("ENTER THE HEIGHT"))
print("NAME :",name)
print("AGE : ",age)
print("WEIGHT : ",weight)
print("HEIGHT : ",height)
bmi=weight/(height**2)*703
print(f"the age of {name} after 1 year is {age + 1} and the age after 5 years is {age + 5}")
print("difference between current and goal weight is", weight - gw)
print("BMI : ",bmi)
print(type(name))
print(type(age))
print(type(weight))
print(type(gw))