print(" Interactive Profile Calculator ")
name=input("ENTER YOUR NAME")
age=int(input("ENTER THE AGE"))
city=input("ENTER THE CITY NAME")
a=int(input("enter the years you in future"))
print("NAME :",name)
print("AGE : ",age)
print("CITY : ",city)
print(f"the age of {name} after {a} is {a+age}")